# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20161127_2259'),
        ('blog', '0018_user'),
    ]

    operations = [
    ]
